server:
  port: 8083
  address: 192.168.8.129
base-url:
  context: /api/library/v1.0

micro_sercice:
  port: 8080
  address: 34.28.43.123

spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/library?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    maxIdle: "10"
    maxActive: "20"
    maxWait: "2000"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

log:
 identifierKey: UUID

python:
  pluginFilePath: "C:\\Personal\\Msc\\Project\\server\\server\\src\\main\\java\\com\\janitha\\videoenhancer\\client\\external\\cloudletPlugins"
  pythonPath : "C:\\Users\\janitha\\AppData\\Local\\Programs\\Python\\Python310\\python"
